[tool.poetry]
name = "gnn-recommender"
version = "0.1.0"
description = ""
authors = ["Anna Sidorova <anna.pav.sidorova@gmail.com>"]
readme = "README.md"
packages = [
    { include = "eda" },
    { include = "docs" }
]

[tool.poetry.dependencies]
python = "^3.10"
polars = "^1.18.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.5"
black = "^23.9.1"
pre-commit = "^4.0.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core"]

[tool.black]
line-length = 99
target-version = ["py310"]
