[project]
name = "nfarec-cuda"
version = "0.1.0"
description = ""
authors = [
    {name = "Roman Tishin",email = "tishin-r@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.9, <3.13"
dependencies = [
    "alembic (==1.11.3)",
    "bottleneck (==1.3.7)",
    "cmaes (==0.10.0)",
    "colorlog (==6.7.0)",
    "fsspec (==2023.10.0)",
    "greenlet (==2.0.2)",
    "huggingface-hub (==0.17.3)",
    "markupsafe (==2.1.1)",
    "mako (==1.2.4)",
    "networkx (==3.1)",
    "numpy (==1.25.2)",
    "optuna (==3.3.0)",
    "packaging (==23.1)",
    "pillow (==9.4.0)",
    "pyyaml (==6.0.1)",
    "regex (==2023.10.3)",
    "requests (==2.31.0)",
    "safetensors (==0.4.0)",
    "scipy (==1.11.2)",
    "setproctitle (==1.3.3)",
    "sqlalchemy (==2.0.20)",
    "sympy (==1.11.1)",
    "tqdm (==4.66.1)",
    "torch (==2.0.1)",
    "torchaudio (==2.0.2)",
    "torchvision (==0.15.2)",
    "transformers (==4.35.0)",
    "typing-extensions (==4.7.1)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.1.0"
